/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RE08_Group3_A2;

import RE08_Group3_A2.Product.Product;
import RE08_Group3_A2.ReadAndWriteTXT.ReadTXT;
import RE08_Group3_A2.ReadAndWriteTXT.WriteTXT;
import RE08_Group3_A2.User.User;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;
import java.util.HashMap;

class AppTest {
    /*@Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }*/
    @Test
    void writeUserTest(){
        WriteTXT wt = new WriteTXT();
        ReadTXT rd = new ReadTXT();
        HashMap<Integer, User> userMap = rd.readUserTXT();
        wt.writeUserTXT(userMap);
    }

    @Test
    void writeProductTest(){
        WriteTXT wt = new WriteTXT();
        ReadTXT rd = new ReadTXT();
        HashMap<Integer, Product> productMap = rd.readProductTXT();
        wt.writeProductTXT(productMap);
    }

    @Test
    void writeMoneyTest(){
        WriteTXT wt = new WriteTXT();
        ReadTXT rd = new ReadTXT();
        HashMap<BigDecimal, Money> moneyMap = rd.readMoneyTXT();
        wt.writeMoneyTXT(moneyMap);
    }
}
