/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RE08_Group3_A2;

import RE08_Group3_A2.Product.Product;
import RE08_Group3_A2.ReadAndWriteTXT.*;
import RE08_Group3_A2.User.Cashier;
import RE08_Group3_A2.User.Seller;
import RE08_Group3_A2.User.User;
import RE08_Group3_A2.View.LoginView;

import java.math.BigDecimal;
import java.util.HashMap;

public class App {
    VendingMachine vendingMachine;
    public static App instance;
    public static void main(String[] args) {
        App app = new App();
        app.run();

    }
    public void run() {
        ReadTXT rd = new ReadTXT();
        HashMap<Integer, User> users = rd.readUserTXT();
        HashMap<Integer, Product> products = rd.readProductTXT();
        HashMap<BigDecimal, Money> moneys = rd.readMoneyTXT();
        this.vendingMachine = new VendingMachine(products, users, moneys);
        this.vendingMachine.initializeNumberOfCategory();
        Cashier cs = new Cashier("abc", 123, "abc123");
        cs.getReportOfTheTransaction(this.vendingMachine);

        LoginView LV = new LoginView(vendingMachine);
        LV.LoginViewPlot();


//        Seller sl = new Seller("aa", 123, "123aaa");
//        Product pd = new Product("Sprite", "Drinks",2.5, 1001,2);
    }

    public static App getInstance() {
        return instance;
    }

    public VendingMachine getVendingMachine(){
        System.out.println(this.vendingMachine==null);
        return vendingMachine;
    }


}
